Don't use valid category numbers for SII_PREAMBLE and SII_STD_CONFIG
synapticon/siitool pull request #14
Opened 2021-08-16 10:37 UTC by mheden

According to Table 19 in ETG1000/6 the values used for SII_PREABMLE and
SII_STD_CONFIG could be allocated as "Device specific" categories. This
patch assigns them new numbers that don't clash with valied categories.

Without this patch, the tool will hang if an eeprom have category 1
entries.

2021-08-18 07:07 UTC, fjes commented
Hello @mheden , thanks for the pull-request. Can you please point to a SII where these categories are set? I would like to test a little bit with that.

2021-08-18 09:04 UTC, mheden commented
Hi @fjes,

Unfortunately I don't have any officially made eeprom images for this but I've made one by myself ([eeprom_ax58100.zip](https://github.com/synapticon/siitool/files/7005913/eeprom_ax58100.zip)) that I think is correct. If you run `./siitool -p eeprom_ax58100.bin`, the tool will hang since it will always go back and try to parse the preamble.

I'm currently working with the AX58100 and they use "category 1" for some reason:
![image](https://user-images.githubusercontent.com/8748209/129869845-e909d1e9-4d9b-40a0-9ae1-0723339b97fb.png)

2021-08-20 09:29 UTC, fjes requested changes
Thanks again for the finding, good catch. Unfortunately the index range 0x0800 - 0x1FFF is in the Vendor specific region (see table 5 in ETG2010 v1.0.0). The two symbols `SII_PREAMBLE` and `SII_STD_CONFIG` are internal control symbols.
What do think of assining them to `SII_PREAMBLE = -1` and `SII_STD_CONFIG = -2`? Since these values are not written into the final binary I assume this would be the cleaner solution for now.

2021-08-20 10:46 UTC, mheden commented
Indeed, that's why I put them at `0x10000` and `0x10001` which is outside the valid range (`0-0xffff`).

But I agree, it looks nicer to have them as negative numbers. I'll updated the patch.

2021-08-20 13:19 UTC, fjes approved these changes
Thanks.

2021-08-20 13:20 UTC, merged